testpress/iOSPlayerSDK

Source/Managers/TPStreamPlayer.swift
Source/Views/MediaControlsView.swift

- Implemented a loading indicator in the player to display when the playback buffer is empty until it loads data to play.
- This is accomplished by changing the player status to "buffering" when `isPlaybackBufferEmpty` in the AVPlayer becomes true. The status reverts back to its previous state when `isPlaybackLikelyToKeepUp` becomes true.

feat: Show loading indicator while player buffering

---

Source/TPStreamPlayerView.swift

- On iOS 16 or later, changing orientation using `UIDevice` is deprecated. Therefore, we have implemented the `requestGeometryUpdate` method for the same.
- For older iOS versions, we continue to use the previous process.

fix: Maximize button failing to switch orientation to landscape in iOS 16

---

Source/Managers/TPStreamPlayer.swift

- Currently, the interval for addPeriodicTimeObserver was set to trigger every nanosecond which resulted in the main thread being blocked and preventing the execution of other code.
- This is fixed by reducing the interval to 0.5 seconds.

fix: Playback speed options not showing while video playing

---

Source/Managers/TPStreamPlayer.swift
Source/Views/MediaControlsView.swift
Source/Views/PlayerControlsView.swift
Source/Views/PlayerProgressBar.swift
Source/Views/PlayerSettingsButton.swift
Source/Views/TimeIndicatorView.swift

- Currently, Player control methods and observers are present inside `TPStreamsPlayer` which is also an Observable object and the use of observable objects is only available from iOS 14 onwards, also we cannot use observable objects with a UIView.
- So extracted observable attributes to separate class, now we can use the `TPStreamsPlayer` class with UIView and iOS 11.

fix: Extract TPStreamsPlayer obserable attributes to separate class

---

Source/Managers/TPStreamPlayer.swift
Source/Views/SwiftUI/MediaControlsView.swift

- Converted TPStreamsPlayer `status` and `currentTime` to observable primitive data types for observation and UIView updates.

refactor: Convert TPStreamsPlayer attributes to observable primitive data types

---

Source/TPAVPlayer.swift
TPStreamsSDK.podspec

- Added podspec file for our package to release it in Cocoapods.
- Added a compiler flag to import M3U8Parser dependency using the name `M3U8Kit` while building the package for Cocoapods to prevent import errors as they have named the package with a different name in Cocoapods.
- Raised an issue in the M3U8Parser repository to resolve this naming inconsistency between different package managers, [issue](https://github.com/M3U8Kit/M3U8Parser/issues/38).

feat: Release Package in cocoapods

---

Source/TPStreamsSDK.swift
TPStreamsSDK.podspec

- Previously, resources were not properly bundled within the package, causing errors when attempting to use images from the package in the app.
- This commit bundles images and other resources within the package and initializes the bundle using the bundle URL when the package is integrated via CocoaPods.

fix: Error while using package via cocoapods

---

Source/Managers/ResourceLoaderDelegate.swift
Source/TPAVPlayer.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Added AES Encryption support: AVPlayer by default requests a decryption key from the key URL specified in the manifest.but that request will fail with an unauthorized error, So we intercept it and attach an 'access_token' query parameter for authorization using the Resource Loader delegate.

feat: Add support to play AES-Encrypted videos

---

Source/Extensions/UIInterfaceOrientationMask.swift
Source/Extensions/UIView.swift
Source/TPStreamPlayerView.swift
Source/TPStreamPlayerViewController.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Previously, player orientation did not switch to landscape on fullscreen for iOS versions below 16. Below iOS 16, we set the orientation using UIDevice but incorrectly used `UIInterfaceOrientationMask` instead of the correct `UIInterfaceOrientation` rawValue. As a result, the orientation did not change.
- This commit resolves the issue by introducing a method via an extension to obtain the equivalent UIInterfaceOrientation from UIInterfaceOrientationMask then used to retrieve the correct orientation and set its raw value on UIDevice.

fix: Player orientation not changed on fullscreen below iOS 16

---

Source/Views/UIKit/ProgressBar.swift
Source/Views/UIKit/Xib/PlayerControls.xib

- Previously, the draggable thumb extended beyond the allocated width of the progress bar and became slightly hidden when in the starting or ending position. 
- This commit resolves the issue by reducing the progress bar width and providing sufficient space for the thumb to overflow at the starting or ending position

fix: Render dragable thumb properly on progress bar

---

Source/TPStreamPlayerViewController.swift
StoryboardExample/ViewController.swift

-This commit introduces the `TPPlayerViewControllerDelegate` protocol, providing a set of delegate methods to handle fullscreen events in `TPStreamPlayerViewController`. 
- Users can now set a delegate conforming to this protocol to receive notifications when the player view controller is about to enter fullscreen mode, has entered fullscreen mode, is about to exit fullscreen mode, and has exited fullscreen mode, this allows for customization and interaction with fullscreen-related actions.

feat: Introduce TPPlayerViewControllerDelegate for fullscreen events

---

Source/Managers/TPStreamPlayer.swift
Source/Views/UIKit/PlayerControlsUIView.swift

- The commit 4e1ed48 introduced validation for the seek value, setting it to 0.0 if the value is NaN.
- In this commit, we examine the seek value, and if it is NaN, we exit the process. Additionally, we've implemented logic to update the current time if the video duration is initialized.

refactor: Return if player seek value is `NaN`

---

Source/TPAVPlayer.swift
Source/TPStreamPlayerViewController.swift
TPStreamsSDK.podspec
iOSPlayerSDK.xcodeproj/project.pbxproj

- Previously, the error message indicating a network unavailability persisted even after the user reconnected.
- This is fixed in this commit by triggering a re-fetch of video details from the server upon the restoration of network availability following a no-network connection error. As a result, the error view is now properly hidden when the network connection is restored, and the player is loaded with the fetched video details.

fix: Error view persistence on network reconnect

---

Example/ContentView.swift
Source/Database/Model/OfflineAsset.swift
Source/Database/ObjectManager.swift
Source/Database/TPStreamsDownloadManager.swift
Source/Managers/TPStreamPlayer.swift
Source/TPStreamPlayerConfiguration.swift
Source/TPStreamsSDK.swift
Source/Views/SwiftUI/PlayerSettingsButton.swift
Source/Views/UIKit/PlayerControlsUIView.swift
StoryboardExample/ViewController.swift
Tests/ObjectManagerTest.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- In this commit, we added Offline download support for Non-DRM videos via API
- Added Test case for add and get object operations

feat: Add Non-DRM video download support

---

Source/Managers/ContentKeyDelegate.swift
Source/TPAVPlayer.swift
Source/TPStreamPlayerError.swift
Source/TPStreamsSDK.swift
Source/Utils/Sentry.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Added support for capturing player errors in Sentry in this commit. Additionally, pass along some information such as orgCode, assetID, and access token of the current playback.
- Disabled attachScreenshot and attachViewHierarchy. Enabling these features was causing issues with the Sentry capture error method.

fix: Capture player errors in sentry

---

Source/Managers/TPStreamPlayer.swift
Source/Network/Models/Asset.swift
Source/TPAVPlayer.swift

- Passed the live stream HLS URL to the player for live stream assets that are currently streaming.
- Modified the video duration fetching logic to correctly handle live streaming durations, as they differ from on-demand video duration.

feat: Add support to play live stream

---

Package.swift
TPStreamsSDK.podspec
iOSPlayerSDK.xcodeproj/project.pbxproj

- Updated Sentry to version 8.36.0, as the previous version caused an error when running the app with our package in Xcode 16. The latest version includes a fix for this issue.

Update Sentry to version 8.36.0

---

Package.swift
Source/Database/Models/OfflineAsset.swift
Source/Database/Models/OfflineAssetEntity.swift
Source/Database/ObjectManager.swift
Source/TPStreamsSDK.swift
TPStreamsSDK.podspec
iOSPlayerSDK.xcodeproj/project.pbxproj

- In this commit, we added the Realm database via the swift package manager.
- Added `LocalOfflineAsset` model and Initialize Realm database in `TPStreamsSDK`.
- Added Generic ObjectManager class for adding, getting, and updating objects from the database.
- Added Realm database dependencies in `Package.swift` and `TPStreamsSDK.podspec` files.
- Added the `OfflineAsset` model from external use

feat: Add Realm Database and OfflineAsset model

---

Example/AppDownloadManager.swift
Example/Views/OfflineAssetRow.swift
Source/Database/ObjectManager.swift
Source/Database/TPStreamsDownloadManager.swift

- In this commit, we added a delete option for the download videos
- Added `deleteDownload(offlineAssetId)` method in `TPStreamsDownloadManager` this method can be used to delete the downloaded video

feat: Add support to delete the downloaded video

---

Source/Database/Models/OfflineAsset.swift
Source/Database/TPStreamsDownloadManager.swift
Source/TPStreamsSDK.swift

- Added a deleted status to the `Status` enum for identifying marked assets.
- Implemented `removePartiallyDeletedVideos()` in `TPStreamsDownloadManager` to delete assets with the deleted status and remove corresponding files from the filesystem.
- Modified `deleteDownload()` to update asset status to deleted instead of immediate removal for better tracking.
- Updated `getAllOfflineAssets()` to exclude assets with a deleted status, returning only active assets.
- Integrated cleanup logic into the SDK initialization process to handle deleted assets at startup.

fix: Remove Partially Deleted Video

---

Source/Managers/ResourceLoaderDelegate.swift
Source/Network/BaseAPI.swift
Source/Network/TestpressAPI.swift
Source/TPAVPlayer.swift
Source/TPStreamsSDK.swift

- Implemented support for including a JWT authorization token in API requests.
- Updated the `initialize` method to accept an optional `authToken`.
- Added an authorization header to all request headers based on the availability of the `authToken`.
- Updated the API endpoint URL to include a trailing slash after the video ID, ensuring correct server interpretation and avoiding 401 Unauthorized responses.

feat: Add JWT Authorization Support for API Requests

---

Example/AppDownloadManager.swift
Example/Views/OfflineAssetRow.swift
Source/Database/TPStreamsDownloadManager.swift

- Added `cancelDownload(assetId:)` method in `TPStreamsDownloadManager`.
- Introduced `onCanceled(assetId:)` method in `TPStreamsDownloadDelegate`.
- Improves user experience by enabling download cancellation and cleaning up partially downloaded files.

enhancement: Add cancel download functionality for Offline download

---

Source/Managers/TPStreamPlayer.swift
Source/Views/SwiftUI/PlayerSettingsButton.swift
Source/Views/UIKit/PlayerControlsUIView.swift

- Introduces a download option in the player view, accessible via the settings button.
- The download option is enabled by default in both Storyboard and SwiftUI.

feat: Add download button in player view

---

Example/Views/PlayerView.swift
Source/TPStreamPlayerConfiguration.swift
Source/Views/SwiftUI/PlayerControlsView.swift
Source/Views/SwiftUI/PlayerSettingsButton.swift
Source/Views/UIKit/PlayerControlsUIView.swift
StoryboardExample/PlayerViewController.swift

- Implemented the ability to show or hide the download option in the player settings based on configuration.
- Added `.showDownloadOption()` to `TPStreamPlayerConfigurationBuilder` to enable or disable the download button in both `SwiftUI` and `UIKit` player controls.
- Updated `PlayerSettingsButton` and `PlayerControlsUIView` to conditionally display the download quality option when configured.
- Integrated the download option feature in both `Storyboard` and `SwiftUI` implementations.

enhancement: Add download option to player configuration

---

Source/TPAVPlayer.swift
Source/Views/SwiftUI/PlayerSettingsButton.swift
Source/Views/UIKit/PlayerControlsUIView.swift

- Added a new property `isPlaybackOffline` to differentiate between offline and online playback modes.
- Updated `PlayerSettingsButton` and `PlayerControlsUIView` to conditionally display video quality and download options only during online playback.
- Refactored the options menu to include online-specific settings when the player is not in offline mode.

enhancement: Differentiate Offline and Online Player Settings

---

Example/Views/PlayerView.swift
Source/Database/TPStreamsDownloadManager.swift

- Removed the startDownload method from TPStreamsDownloadManager.swift, which was added earlier as a placeholder for downloading functionality.

refactor: Remove Placeholder StartDownload Method

---

Source/Database/Models/OfflineAssetEntity.swift
Source/Network/Models/Video.swift
Source/Network/Parsers/StreamsAPIParser.swift
Source/Network/Parsers/TestpressAPIParser.swift

- Added `drmContentId` property to the `Video` model and `LocalOfflineAsset` database entity.
- Updated API parsers (`StreamsAPIParser` and `TestpressAPIParser`) to handle `drm_content_id` field in API responses.
- This `drmContentId` is used to facilitate offline DRM license downloads for FairPlay-protected content.

fix: Add drmContentId field in Video Model

---

Source/Network/Models/Asset.swift
Source/Network/Models/Video.swift
Source/Network/Parsers/StreamsAPIParser.swift
Source/Network/Parsers/TestpressAPIParser.swift

- Moved the `drmContentId` property from the Video model to the Asset model.
- Updated the `StreamsAPIParser` and `TestpressAPIParser` to parse and assign `drmContentId` at the Asset level.
- Removed the `drmContentId` property from the Video model to streamline DRM handling.

refactor: Move `drmContentId` from Video to Asset Model

---

Source/TPStreamsSDK.swift

- Introduced a `validateAuthToken()` method to ensure that when the provider is `.tpstreams`, the `authToken` must be `nil`.
- This validation prevents potential misconfigurations by enforcing correct usage of the `authToken` based on the provider.

fix: Add Validation for Auth Token Based on Provider

---

Source/Managers/ResourceLoaderDelegate.swift
Source/TPAVPlayer.swift

- Updated `accessToken` in `ResourceLoaderDelegate` and `TPAVPlayer` to be optional (`String?`). In `TPAVPlayer`, a check is added to raise an error if both the `accessToken` and the global `authToken` are missing. This improves flexibility while ensuring at least one token is provided.

fix: Improve Access Token and Auth Token Validation in TPAVPlayer

---

Source/TPAVPlayer.swift
Source/TPStreamPlayerViewController.swift
Source/Utils/Sentry.swift
Source/ViewModels/TPStreamPlayerViewModel.swift

- Added a UUID to the Sentry event context to improve error traceability. The UUID, along with the error message, is now displayed in the player view controller, enabling easy correlation with specific Sentry events.
- Modified the initialization error handling to store both the error and the Sentry issue ID. This allows the player to show the error and Sentry issue ID even if the player is assigned to the view controller after the error occurs.

fix: Include UUID in Sentry events for better traceability

---

Source/Database/TPStreamsDownloadManager.swift
Source/Managers/ContentKeyDelegate.swift
Source/Managers/ResourceLoaderDelegate.swift
Source/Network/BaseAPI.swift
Source/TPAVPlayer.swift
Source/Views/SwiftUI/PlayerSettingsButton.swift
Source/Views/UIKit/PlayerControlsUIView.swift

- Users can now access videos without an access token by providing an auth token.
- This commit makes the `accessToken` an optional field wherever required across all relevant areas.

fix: Make accessToken an Optional Field

---

Source/TPAVPlayer.swift

-  Raised an error if both authToken and accessToken are missing during player initialization. If the authToken is already set, the accessToken becomes optional, ensuring proper initialization without unnecessary constraints.

fix: Raise error if access token not provided during initialization

---

Source/Database/TPStreamsDownloadManager.swift
Source/Views/SwiftUI/PlayerSettingsButton.swift
Source/Views/UIKit/PlayerControlsUIView.swift
StoryboardExample/MainViewController.swift

- The app was crashing when running in the iOS Simulator due to the usage of AVContentKeySession in SDK initialization, which is not supported in simulator environments.
- This has been resolved by conditionally initializing DRM-related components using compiler directives, ensuring they are only created on real devices while allowing non-DRM download functionality to work normally in the simulator. The fix maintains full DRM support on physical devices while enabling development and testing of download features in the simulator environment.

fix: App crash while running in Simulator

---

Package.swift
TPStreamsSDK.podspec
iOSPlayerSDK.xcodeproj/project.pbxproj

- Bumped Realm Swift dependency from version 10.45.0 to 10.54.2 in Package.swift, TPStreamsSDK.podspec, and Xcode project configuration
- Updated Code sign property and Xcode configuration to support the latest Realm package, as they have changed the package from static to dynamic

fix: Update Realm Swift to version 10.54.2

---

Source/Database/Models/OfflineAsset.swift
Source/Database/Models/OfflineAssetEntity.swift
Source/Database/TPStreamsDownloadManager.swift
Source/Network/Models/Video.swift
Source/Network/Parsers/StreamsAPIParser.swift
Source/Network/Parsers/TestpressAPIParser.swift
Source/TPStreamsSDK.swift

- iOS SDK offline assets did not include thumbnail URL, creating inconsistency with Android and React Native.
- Added thumbnail URL support to ensure consistent download(offlineAsset) details across platforms.

feat: Add thumbnail URL support for offline assets

---

Source/Database/Models/OfflineAsset.swift
Source/Database/Models/OfflineAssetEntity.swift
Source/Database/TPStreamsDownloadManager.swift
Source/Extensions/AnyRealmValue.swift
Source/TPAVPlayer.swift
Source/TPStreamPlayerConfiguration.swift
Source/TPStreamsSDK.swift
Source/Views/SwiftUI/PlayerSettingsButton.swift
Source/Views/UIKit/PlayerControlsUIView.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Download items in mobile platforms support attaching custom metadata, which allows user to store additional context with offline assets.
- iOS lacked this support, and this change adds it to ensure consistency and a unified cross-platform experience.

feat: Add metadata support for offline assets

---

Source/Database/Models/OfflineAssetEntity.swift
Source/TPStreamsSDK.swift

- DRM licenses for offline content have expiration dates that need to be tracked to ensure valid playback and enable license renewal workflows. Without storing the expiry date, the SDK cannot proactively manage license validity or provide users with timely renewal notifications.
- This change enables the SDK to track when offline DRM licenses expire, allowing for better user experience through proactive license management and preventing playback failures due to expired licenses.

feat: Add license expiry date field for offline DRM license tracking

---

Source/Database/TPStreamsDownloadManager.swift
Source/Managers/ContentKeyDelegate+Persistable.swift
Source/Managers/ContentKeyDelegate.swift
Source/Network/BaseAPI.swift
Source/TPStreamPlayerConfiguration.swift
Source/Views/SwiftUI/PlayerSettingsButton.swift
Source/Views/UIKit/PlayerControlsUIView.swift

- Add support for specifying DRM license expiry for offline content, allowing users to set an expiration time for offline assets. 
- This ensures that content becomes inaccessible after the defined period, helping enforce proper access control.

feat: Add DRM license expiry support for offline content
