testpress/iOSPlayerSDK

Source/Extensions/AVPlayer.swift
Source/Managers/TPStreamPlayer.swift
Source/Views/PlayerControlsView.swift
Source/Views/PlayerProgressBar.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Added a custom progress bar to the player with seek functionality and display of watched and buffered duration.

feat: Add progress bar with seek-through support

---

Source/Managers/TPStreamPlayer.swift
Source/TPAVPlayer.swift
Source/Views/PlayerSettingsButton.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Added a video resolution option to the player.
- Integrated with M3U8Parser package to extract available resolutions from the master playlist and displayed extracted resolutions as selectable options for users.
- Updated the video bitrate according to user selection, with the default option being "auto" to automatically choose the resolution based on the user's network.

feat: Add support to change resolution

---

StoryboardExample/AppDelegate.swift
StoryboardExample/Assets.xcassets/AccentColor.colorset/Contents.json
StoryboardExample/Assets.xcassets/AppIcon.appiconset/Contents.json
StoryboardExample/Assets.xcassets/Contents.json
StoryboardExample/Base.lproj/LaunchScreen.storyboard
StoryboardExample/Base.lproj/Main.storyboard
StoryboardExample/Info.plist
StoryboardExample/SceneDelegate.swift
StoryboardExample/ViewController.swift

- Created a sample app using storyboard and set minimum deployment version 11.4 and integrated with our player SDK.

fix: Create sample app with storyboard to test our SDK

---

Source/TPStreamPlayerViewController.swift
Source/TPStreamUIKitPlayerView.swift
Source/Views/PlayerControlsUIKitView.swift
Source/Views/Xib/PlayerControls.xib
StoryboardExample/ViewController.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Created a custom UIView that acts as a player interface. This custom view displays two subviews, TPVideoPlayerUIView and PlayerControlsView, arranged in a Z-axis arrangement. 
- By default, the PlayerControlsView is hidden, and it remains hidden until the user taps on the screen.

feat: Create player with a storyboard

---

Source/TPStreamPlayerViewController.swift
Source/Views/UIKit/PlayerControlsUIView.swift
Source/Views/UIKit/Xib/PlayerControls.xib

- Added support to play or pause the video through UI.

feat: Add support to play or pause the video

---

Source/Utils/Time.swift
Source/Views/SwiftUI/TimeIndicatorView.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Extracted method from the view, since we can use the same method in the UIView player.

refactor: Extract util method from view

---

Source/Views/UIKit/PlayerControlsUIView.swift

- Added support to change video resolution via player UI by showing an action sheet with available resolutions to change.

feat: Add support to change video resolution

---

Source/Managers/TPStreamPlayer.swift
Source/Views/UIKit/PlayerControlsUIView.swift
Source/Views/UIKit/Xib/PlayerControls.xib

- Displayed video duration in player UI after its initialization.
- Showed and updated the current time in player UI on every change.

feat: Show video duration and current time in player

---

Source/Extensions/UIView.swift
Source/TPStreamPlayerViewController.swift
Source/Views/UIKit/PlayerControlsUIView.swift
Source/Views/UIKit/Xib/PlayerControls.xib

- Added support to change toggle fullscreen by clicking on maximize/minimize or by changing device orientation.
- Enabled fullscreen for player view regardless of parent view size by extracting it as an attribute and setting it on the key window UIView.

feat: Add support to toggle fullscreen

---

Source/Views/UIKit/Xib/PlayerControls.xib

- Positioned duration labels and actions button below the progress bar.
- Reduced the length of the progress bar to accommodate smaller screens.

fix: Modify player controls UI

---

Source/Views/UIKit/ProgressBar.swift

- Watched progress length mismatch post video completion during an orientation change. The issue arose as the watched progress width was calculated on the player's current time change, leading to the same width being retained even after the overall progress width changed due to orientation adjustments.
- This is fixed by calling setNeedDisplay on progressBar width change to redraw the watched/buffered duration width based on the current size. Additionally, instead of storing watched/buffered width as a class variable, it is now calculated before applying it to the progress bar, ensuring accurate width calculation based on the current progress bar width.

fix: Watched progress length differs between orientation change

---

Source/TPStreamPlayerConfiguration.swift
Source/Views/UIKit/PlayerControlsUIView.swift
Source/Views/UIKit/ProgressBar.swift
StoryboardExample/ViewController.swift

- Added support to configure progress watched track and draggable thumb colour via player configuration class.

feat: Support to configure progress bar

---

.github/workflows/ios_test.yml
TPStreamsSDK.xctestplan
Tests/iOSPlayerSDKTests.swift
iOSPlayerSDK.xcodeproj/project.pbxproj
iOSPlayerSDK.xcodeproj/xcshareddata/xcschemes/iOSPlayerSDKTests.xcscheme

- In this commit, we added GitHub Actions to run test cases for each pull request.

test: Add basic test case and github actions

---

.github/workflows/ios_test.yml

- Changed branch name to main in test case GitHub actions

refactor: Change branch name to main

---

Source/TPAVPlayer.swift

- This commit introduces the addition of the asset field to `TPAVPlayer`, enabling access to the asset from any part of the player.
- Furthermore, the asset parameters have been removed from `setup()` since the asset is now a class member that can be accessed directly.

enhancement: Add asset field to `TPAVPlayer`

---

Source/Network/Models/Asset.swift
Source/Network/StreamsAPI.swift
Source/Network/TestpressAPI.swift

- In this commit, we are adding the duration field in the asset model.
- Hereafter we can access the duration in the necessary locations without player.

enhancement: Add `duration` field asset model

---

Source/Network/BaseAPI.swift
Source/Network/Parsers/BaseAPIParser.swift
Source/Network/Parsers/StreamsAPIParser.swift
Source/Network/Parsers/TestpressAPIParser.swift
Source/Network/StreamsAPI.swift
Source/Network/TestpressAPI.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Extracted parsing-related code from the Network classes.
- Created new Parser classes to handle parsing logic.
- This change anticipates future additions for parsing live streams and other details.

refactor: Extract parsing-related code from Network class

---

Source/Network/Models/Asset.swift
Source/Network/Parsers/BaseAPIParser.swift
Source/Network/Parsers/StreamsAPIParser.swift
Source/Network/Parsers/TestpressAPIParser.swift
Source/Network/TestpressAPI.swift
Source/TPAVPlayer.swift

- Introduced the LiveStream data class to parse live stream details from the API, as we require these details to implement live support.

fix: Store Live Stream details from API in Asset data class

---

Source/Managers/TPStreamPlayer.swift
Source/Views/SwiftUI/TimeIndicatorView.swift
Source/Views/UIKit/LiveIndicatorView.swift
Source/Views/UIKit/PlayerControlsUIView.swift
Source/Views/UIKit/Xib/PlayerControls.xib
iOSPlayerSDK.xcodeproj/project.pbxproj

- Added live stream indicator label to both Storyboard and SwiftUI players, also implemented a functionality to seek to live edge when the user clicks on the live label.

feat: Add live stream indicator label to players

---

Example/AppDownloadManager.swift
Example/Views/DownloadListView.swift
Example/Views/OfflineAssetRow.swift
Source/Database/TPStreamsDownloadManager.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

In this commit we added `TPStreamsDownloadDelegate` to monitor the download state changes we included methods for download start, pause, resume, complete

feat: Add `TPStreamsDownloadDelegate`

---

Example/AppDownloadManager.swift
Example/Views/OfflineAssetRow.swift
Example/Views/PlayerView.swift
Source/Database/Models/OfflineAssetEntity.swift
Source/Database/TPStreamsDownloadManager.swift
Source/TPAVPlayer.swift
Source/TPStreamPlayerError.swift

- In this commit, we added support to play downloaded video
- Added a new constructor with offlineAssetId param in TPAVPlayer

feat: Add support play downloaded non drm video

---

StoryboardExample/Base.lproj/Main.storyboard
StoryboardExample/MainViewController.swift
StoryboardExample/PlayerViewController.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Created a separate Main View Controller with three sample video buttons and one downloads button, making the Player View Controller reusable.

refactor: Update Storyboard Exam App UI

---

StoryboardExample/AppDownloadManager.swift
StoryboardExample/Base.lproj/Main.storyboard
StoryboardExample/DownloadListViewController.swift
StoryboardExample/MainViewController.swift
StoryboardExample/PlayerViewController.swift
StoryboardExample/Utils/Time.swift
iOSPlayerSDK.xcodeproj/project.pbxproj

- Added a download list view with options to cancel and delete downloads
- Enabled functionality to play offline videos from the list

enhancement: Add Download List View in Storyboard Example App

---

Example/Views/PlayerView.swift
Source/TPStreamPlayerView.swift
Source/Views/SwiftUI/MediaControlsView.swift
Source/Views/SwiftUI/PlayerControlsView.swift
Source/Views/SwiftUI/PlayerProgressBar.swift

- Previously, users could only configure their player view in the storyboard implementation. With this commit, we've added support for SwiftUI.
- Users can now configure their SwiftUI player view, including options to customize the progress bar color and set custom forward and rewind values.

enhancement: Implement Player View Configuration for SwiftUI

---

Example/Views/OfflineAssetRow.swift
Example/Views/PlayerView.swift
Source/Database/TPStreamsDownloadManager.swift
StoryboardExample/PlayerViewController.swift

- Added a new `isAssetDownloaded()` method in `TPStreamsDownloadManager` to streamline and centralize the video download status check.
- Updated relevant code in Sample Apps accordingly.

fix: Introduce Method to Verify Video Download Status
